### PR TITLE
update to 1.0.0b3

### PR DESCRIPTION
**Pull request by chrisjsewell**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
@conda-forge-admin, please rerender

**Comment by chrisjsewell** [comment]
Hey @ltalirz even though you added me as a maintainer, I haven't been added to @conda-forge/aiida-core, to get merge privileges. I'm guessing it's because I'm only listed as a maintainer on the `dev` branch.

**Comment by ltalirz** [comment]
I hope this merge fixes it ;-) If not, let me know

**Comment by ltalirz** [comment]
Ah, I'll need to update in master at some point (I can't add you by hand it seems)

**Pull request merged**
