### PR TITLE
try enabling python 3.8

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerun bot

**Comment by ltalirz** [comment]
@astamminger Just checking whether you happen to have any magic solutions up your sleeve to make this build work. 
Like last time, it complains about a number of conflicts/unsatisfiable dependencies
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=144760&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c7d0fcb4-3a10-5b26-dfea-e879a93fc2ab&l=836

**Comment by astamminger** [comment]
Hi @ltalirz 

*//rant on*
I have to admit that I've never seen something more useless than those conda conflict error reports...
*//rant off*

Anyway, I did a quick scan of the required packages. In short, here's what I got
```
...
Loading channels: ...working... done                                             
# Name                       Version           Build  Channel                    
plumpy                        0.14.5          py27_0  conda-forge                
plumpy                        0.14.5          py27_1  conda-forge                
plumpy                        0.14.5          py36_0  conda-forge                
plumpy                        0.14.5          py36_1  conda-forge                
plumpy                        0.14.5          py37_1  conda-forge
...
```
Seems like ``python 3.8`` builds are not enabled for ``plumpy`` (If i remember correctly, this was also the issue when we tried to build for ``python 3.7`` couple of weeks ago, wasn't it? Confident that building ``plumpy`` for ``3.8`` should fix the failing build :) ). 

Cheers

**Comment by ltalirz** [comment]
thanks a lot for the hint!

I'm trying this [here](https://github.com/conda-forge/plumpy-feedstock/pull/33) but it does not even start a python 3.8 build - I think because there are two dependencies of plumpy that are missing a python38 build:

 * pika
 * frozendict

both of which I am a maintainer :-D

**Comment by ltalirz** [comment]
Hm, no, I read the output of conda search wrong... both pika and frozendict have version-independent (noarch) builds.
@astamminger Can you spot why plumpy doesn't want to build a python38 version?

**Comment by astamminger** [comment]
@ltalirz To me it seems like the conda-forge rebuild for ``python 3.8`` was never triggered for the ``plumpy``-feedstock.

**Comment by astamminger** [comment]
@conda-forge-admin, please restart ci

**Comment by ltalirz** [comment]
My god, @astamminger strikes again :-)

Thanks a lot

**Pull request merged**
