### PR TITLE
Add aiida-core.atomic_tools sub-package

### PR DESCRIPTION
**Pull request by chrisjsewell**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
@conda-forge-admin, please rerender

**Comment by chrisjsewell** [comment]
@astamminger what do you think of this?
It is really desirable to have this, to create conda packages for plugins that have an `install_requires` against `aiida-core[atomic_tools]` (like aiida-fleur, aiida-nwchem, etc).

Currently, you would need to use this like: `conda install aiida-core aiida-core.atomic_tools`, as opposed to just `conda install aiida-core.atomic_tools`
I think maybe (but not definite) that this is better than adding `aiida-core` to the dependencies of `aiida-core.atomic_tools`, since it is more modular 🤷 

Also, it would be nice to run a test, to check the dependencies and version directly aligns with https://github.com/aiidateam/aiida-core/blob/7772adcae4113404eef27e1e964d7d55734c924c/pyproject.toml#L86
But not sure if this is possible, since you cannot, for instance, really use `pip check` for this: https://github.com/pypa/pip/issues/4086

**Comment by astamminger** [comment]
Hi @chrisjsewell not easy to answer :D 

IMHO I would also opt for the modular approach you suggested (I think we need to update the run_constrained section in ``aiida-core`` to ensure that only the correct version can be installed. I guess we should use your nifty ``pin_subpackage``  there as well, shouldn't we?) On the other hand, having ``aiida-core`` in the deps would more closely mimic the ``pip install aiida-core[atomic-tools]`` behavior. So i guess both ways have their pros and cons and in the end it boils down to personal preference.

Regarding your last point: I think such a test would be a nice feature but at the moment I honestly do not know if and how that could be achieved.

**Comment by chrisjsewell** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
