### PR TITLE
allow builds for python > 3.6

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@sphuber The error is 
```
Package ipython_genutils conflicts for:
ipython[version='>=4.0,<6.0'] -> decorator -> ipython_genutils
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=112105&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c7d0fcb4-3a10-5b26-dfea-e879a93fc2ab&l=1767

Also this might be solved in the next aiida-core release... but [AEP](https://github.com/aiidateam/AEP/pull/10) first!

**Comment by sphuber** [comment]
Don't know exactly what that means, but I know we had to pin `ipython<6.0` because of the `pyzmq` limit of `circus`. But since the latter is now resolved, the `ipython` was unpinned in `aiida-core`. So is that what you are saying? Once we release `aiida-core==1.1.0` this would be fixed?

**Comment by ltalirz** [comment]
Yes, I think/hope so ;)

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
I'm a bit puzzled ... 

It seems like python3.6 works, but python3.7 doesn't - although we're currently testing the conda install on the aiida-core repo [under python3.7](https://github.com/aiidateam/aiida-core/runs/441114729)

I'll disable python 2.7 of course...

**Comment by ltalirz** [comment]
Hm... despite the python version being requested is 3.7
https://github.com/aiidateam/aiida-core/runs/441114729#step:4:1722

I see python 3.6.10 being installed by conda...
https://github.com/aiidateam/aiida-core/runs/441114729#step:4:1991

**Comment by ltalirz** [comment]
Same happens locally: 
```
$ conda env create -n test-env python=3.7 -f environment.yml
...
$ conda activate test-env
$ python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:01:53)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@astamminger This should be working now, *however*:
conda introduced support for the "compatible release" operator (`~=`) only in [version 4.6](https://github.com/conda/conda/releases/tag/4.6.0)  (January 2019).

I.e. installing this recipe with older conda versions will likely fail.
The question is: do we want to translate the dependencies in the environment.yml from `~=1.2.3` into `>=1.2.3, <1.3`?
If there is perhaps already a tool to do that, we could easily incorporate this into the generation of the environment.yml in aiida-core.
If we need to do this by hand, I would probably vote against it.

**Comment by astamminger** [comment]
@ltalirz 

> conda introduced support for the "compatible release" operator (`~=`) only in [version 4.6](https://github.com/conda/conda/releases/tag/4.6.0) (January 2019).

That's actually a very good point and I am a bit concerned that this may indeed lead to issues especially when installing on clusters running older conda versions (at least here ``conda 4.5.4`` is used)

> If there is perhaps already a tool to do that, we could easily incorporate this into the generation of the environment.yml in aiida-core.
> If we need to do this by hand, I would probably vote against it.

So, you're basically taking the version constraints from the generated ``environment.yml`` file and then add them to the ``meta.yaml``? Unfortunately, I honestly do not know about any tool that would automatically transform the version definitions. But I can have a look :)

**Comment by ltalirz** [comment]
> So, you're basically taking the version constraints from the generated environment.yml file and then add them to the meta.yaml?

Yes.

> Unfortunately, I honestly do not know about any tool that would automatically transform the version definitions. But I can have a look :)

Thanks!
If you think it's easier to do this by hand, we can also decide to keep the `environment.yml` in the aiida-core repository unchanged and just update the `meta.yaml` here, with the view of moving to the `~=` operator here as well at some point.

I leave this up to you.

**Comment by astamminger** [comment]
Well, I wrote a short script which does the conversion but after thinking about it a bit I think we should just stick with the ``~=`` pinning. The linter does not complain so it's a valid operator and other packages might also start using it (Although I haven't spotted it so far except for ``kiwipy`` where you're using it for one dependency)

I vote for merge as is and then let's see what happens :P

**Comment by ltalirz** [comment]
Ok, let's go!

**Comment by sphuber** [comment]
Livin' on the edge!

**Pull request merged**
