### PR TITLE
Add services subpackage

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@CJ-Wright since you approved the original PR for this recipe, may I ask you for advice on the change I'm making in this PR?

I'm essentially trying to add what would be an `extra` in `pip` using the `outputs` keyword.
The intention is to have the original `aiida-core` package plus some extra dependencies bundled into `aiida-core.services`  (I might be adding more "outputs" like these in the future).

Does this look reasonable to you?

P.S. I had to remove the `{{ PYTHON }}` variable because it [was no longer recognized](https://travis-ci.com/conda-forge/aiida-core-feedstock/builds/103089144#L434) and led to build failures.

**Comment by CJ-Wright** [comment]
This seems reasonable to me. You might need a rerender for the python thing, I'd add the python syntax back and see what the rerender does. If you want inspiration for `extras` like packages take a look at airflow. https://github.com/conda-forge/airflow-feedstock/blob/master/recipe/meta.yaml

**Comment by ltalirz** [comment]
@CJ-Wright Thanks for the fast reply!

> you might need a rerender for the python thing, I'd add the python syntax back and see what the rerender does. 

Thanks, I tried and rerender does not change anything (both with and without the variable).

> If you want inspiration for extras like packages take a look at airflow. https://github.com/conda-forge/airflow-feedstock/blob/master/recipe/meta.yaml

Thanks, I'm now moving the tests under `aiida-core` like done there, which makes sense.
I see they actually [don't have any `script` key in `build`](https://github.com/conda-forge/airflow-feedstock/blob/78ab32efe86f28826fae3b7f1119a395e710b846/recipe/meta.yaml#L14-L16). Should I perhaps just get rid of it as well?

**Comment by CJ-Wright** [comment]
They have an external script so they don't need the script key, I think you do need the script key.

**Pull request merged**
